In [1]:
import numpy as np
import matplotlib.pyplot as plt
import time as time
%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 3.0)

In [125]:
"""
Achtung: Rechnet lange!
"""
def increasing(N):   
#    print("in: ", N)
    return sum([ (2 * n + 1) / (n**2 * (n + 1)**2) for n in range(1,N) ])
def decreasing(N):   
    print("de: ", N) 
    return sum([ (2 * (N-n) + 1) / ((N-n)**2 * ( N -n + 1)**2) for n in range(1,N) ])

In [ ]:

used = set()
n_rang = [x for x in [int(x) for x in (np.logspace(.1, 11, 200))] if x not in used and (used.add(x) or True)]
np.savetxt("increasing.npy",np.array([[0, 0, 0], [0, 0, 0]]))
for N in n_rang:
    t0 = time.time()
    werte_increasing = 1 - increasing(N) 
    zeit = time.time() - t0
    matrix_alt = np.loadtxt("increasing.npy")
    matrix_neu = np.array([[N, werte_increasing, zeit]])
    np.savetxt("increasing.npy", np.concatenate((matrix_alt, matrix_neu)))
#    np.savetxt("werte_increasing.np", np.array([[np.loadtxt("werte_increasing.np")],
#             [N,werte_increasing, zeit]]))
#    matrix = np.loadtxt("werte_increasing.np")
#    np.savetxt("werte_increasing.np", np.array([[matrix],[np.array([N,werte_increasing, zeit], dtype=float)]]))

#print("now decreas")
#werte_decreasing = [ 1 - decreasing(N) for N in n_rang]
#np.savetxt("werte_N.np", n_rang)
#np.savetxt("werte_decreasing.np", werte_decreasing)
#np.savetxt("zeit.np", np.array([zeit]))
#print(zeit)

In [1]:
plt.plot(n_rang, werte_increasing, "x", alpha = 0.7)
plt.plot(n_rang, werte_decreasing, "x", alpha = 0.7)
#plt.plot(n_rang, 1e-5 + 0*(n_rang), alpha = 0.5)
plt.xlabel("number of summands N")
plt.ylabel("accuracy or error")
plt.loglog()

NameError: name 'plt' is not defined

In [3]:
np.array((np.loadtxt("werte_increasing.np"),np.loadtxt("werte_increasing.np"),))

array([[  3.00000000e+00,   1.11111111e-01,   2.73227692e-04],
       [  3.00000000e+00,   1.11111111e-01,   2.73227692e-04]])

In [13]:
np.array([[np.loadtxt("werte_increasing.np")],[N,werte_increasing, float(zeit)]])

/usr/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: loadtxt: Empty input file: "werte_increasing.np"
  if __name__ == '__main__':


array([list([array([], dtype=float64)]),
       list([1, 1, 7.915496826171875e-05])], dtype=object)

In [31]:
print(zeit, N, increasing(3))

in:  3
0.0003273487091064453 1 0.8888888888888888


In [23]:

with open(outfile+'.x.betas','a') as f_handle:
    np.savetxt(f_handle,dataPoint)

array([], dtype=float64)

In [34]:
my_matrix = np.array([zeit, N, increasing(3)])
my_matrix

in:  3


array([  3.27348709e-04,   1.00000000e+00,   8.88888889e-01])

In [50]:
#np.savetxt("increasing.npy", my_matrix)
matrix0 = np.loadtxt("increasing.npy")
matrix0

array([  3.27348709e-04,   1.00000000e+00,   8.88888889e-01,
         3.27348709e-04,   1.00000000e+00,   8.88888889e-01,
         3.27348709e-04,   1.00000000e+00,   8.88888889e-01])

In [51]:
matrix01 = np.concatenate((my_matrix, matrix0))
matrix01

array([  3.27348709e-04,   1.00000000e+00,   8.88888889e-01,
         3.27348709e-04,   1.00000000e+00,   8.88888889e-01,
         3.27348709e-04,   1.00000000e+00,   8.88888889e-01,
         3.27348709e-04,   1.00000000e+00,   8.88888889e-01])

In [55]:
np.savetxt("increasing.npy", np.concatenate((np.loadtxt("increasing.npy"), matrix0)))

In [56]:
np.loadtxt("increasing.npy")

array([  3.27348709e-04,   1.00000000e+00,   8.88888889e-01,
         3.27348709e-04,   1.00000000e+00,   8.88888889e-01,
         3.27348709e-04,   1.00000000e+00,   8.88888889e-01,
         3.27348709e-04,   1.00000000e+00,   8.88888889e-01,
         3.27348709e-04,   1.00000000e+00,   8.88888889e-01,
         3.27348709e-04,   1.00000000e+00,   8.88888889e-01,
         3.27348709e-04,   1.00000000e+00,   8.88888889e-01,
         3.27348709e-04,   1.00000000e+00,   8.88888889e-01,
         3.27348709e-04,   1.00000000e+00,   8.88888889e-01])

In [112]:
?np.concatenate

In [69]:
print(np.array([0,0,0]))

[0 0 0]


In [76]:
np.loadtxt("increasing.npy")

array([  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         1.00000000e+00,   1.00000000e+00,   1.08718872e-04])

In [110]:
np.concatenate(([matrix_alt], [matrix_neu]))

ValueError: all the input arrays must have same number of dimensions

In [104]:
matrix_alt

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  1.00000000e+00,   1.00000000e+00,   5.86271286e-04]])

In [105]:
matrix_neu

array([  2.00000000e+00,   2.50000000e-01,   4.44650650e-04])

In [116]:
a = np.array([[0, 0, 0], [0, 0, 0]])
b = np.array([[5, 7, 6]])
np.concatenate((a,b))

array([[1, 2, 3],
       [3, 4, 4],
       [5, 7, 6]])

In [118]:
b

array([[5, 7, 6]])